export enum DomainStatusEnum {
  ACTIVE = "ACTIVE",
  IN_USE = "IN_USE",
  CANCELLED = "CANCELLED",
  HELD_EXPIRED_REDEMPTION_MOCK = "HELD_EXPIRED_REDEMPTION_MOCK",
  PENDING_HOLD_REDEMPTION = "PENDING_HOLD_REDEMPTION",
  CANCELLED_REDEEMABLE = "CANCELLED_REDEEMABLE",
}
