name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.8.0
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      
      - name: Install dependencies
        run: pnpm install 
      
      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_BACKEND_URL: 'http://localhost:8000'
          NEXT_PUBLIC_GRAPESJS_LICENSE_KEY: '3be8d9a1f4db47c3b6b26c90232323233fe33ea74ed9ada86c04d1bc7c43'
          NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyA5l5Su123123123fp3A4z2323231bOek0'
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'blogg-233ds34.firebaseapp.com'
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: 'https://blogg-233ds34-default-rtdb.firebaseio.com'
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'blogg-233ds34'
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'blogg-233ds34.appspot.com'
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '10931423211546'
          NEXT_PUBLIC_FIREBASE_APP_ID: '1:1093149911546:web:7e45sdsgv123341957c0f8b1c43'
          NEXT_PUBLIC_REVERB_APP_KEY: 'local_key'
          NEXT_PUBLIC_REVERB_APP_ID: 'local'
          NEXT_PUBLIC_REVERB_HOST: 'localhost'
          NEXT_PUBLIC_REVERB_PORT: '8080'
          NEXT_PUBLIC_REVERB_SCHEME: 'http'
        
      
      # - name: Test
      #   run: pnpm test
      #   env:
      #     MONGODB_URI: mongodb://localhost:27017/testdb
  
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/modobomMDBFE/public_html
            git pull origin main
            git status
            pnpm install
            pnpm build
            pm2 restart cms-fe
           
